# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: custom
day_night: true
font: ''
font_size: XL

# SEO

site_type: Person
local_business_type: ''
org_name: 'Виктория Ильин'
description: 'Я - фотограф и преподаватель, снимаю и учу в онлайн-школе Фотография Новорожденных'
twitter: 'IljinViktoria'

# Site header

main_menu:
  enable: true
  align: r
  show_logo: false
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: false

# Localization

date_format: '2 Jan 2006'
time_format: '15:04'

# Site features

highlight: true
highlight_languages:
  - bash
math: false
diagram: false
privacy_pack: false
require_isotope: false  # Enable if you use Portfolio widget or Publication pages
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    post: false
show_related:
  post: true
email: viktoria.iljin@gmail.com
sharing_image: ''
reading_time: true
section_pager: true
sharing: false
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
plugins_js: []
avatar:
  gravatar: false
  shape: circle
comments:
  provider: ''
  commentable:
    post: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: ''
  api_key: ''
  zoom: 15
marketing:
  google_analytics: 'G-ZY6KEYEBFG'
  google_tag_manager: ''
  google_site_verification: ''
cms:
  netlify_cms: false
icon:
  pack:
    ai: false